"""tasa de cambio BCV

Revision ID: 22aa14939071
Revises: 8c1c0d28abfb
Create Date: 2026-07-20 16:00:46.934784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22aa14939071'
down_revision: Union[str, Sequence[str], None] = '8c1c0d28abfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasas_cambio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('moneda', sa.String(length=8), nullable=False),
    sa.Column('tasa_bolivares', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('fuente', sa.String(length=20), nullable=False),
    sa.Column('fecha_vigencia', sa.Date(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.Column('actualizada_automaticamente', sa.Boolean(), nullable=False),
    sa.Column('mensaje_error', sa.Text(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.CheckConstraint('tasa_bolivares > 0', name='ck_tasa_cambio_positiva'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasas_cambio_moneda_activa', 'tasas_cambio', ['moneda', 'activa'], unique=False)
    op.add_column('pedidos', sa.Column('tasa_bcv_aplicada', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('pedidos', sa.Column('total_bolivares', sa.Numeric(precision=18, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'total_bolivares')
    op.drop_column('pedidos', 'tasa_bcv_aplicada')
    op.drop_index('ix_tasas_cambio_moneda_activa', table_name='tasas_cambio')
    op.drop_table('tasas_cambio')
    # ### end Alembic commands ###
