"""tasa de cambio BCV

Revision ID: 22aa14939071
Revises: 8c1c0d28abfb
Create Date: 2026-07-20 16:00:46.934784

"""
import logging
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22aa14939071'
down_revision: Union[str, Sequence[str], None] = '8c1c0d28abfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Bajo el namespace "alembic." para heredar el nivel INFO y el
# handler de consola que ya configura alembic.ini ([logger_alembic]) —
# un logger con otro nombre quedaría filtrado por el logger_root
# (nivel WARNING) y estos mensajes no se verían en el log de Render.
logger = logging.getLogger("alembic.migration.tasa_bcv")


def upgrade() -> None:
    """
    Idempotente a propósito: esta migración corrió alguna vez contra
    una base donde `tasas_cambio` ya existía (creada por un
    Base.metadata.create_all() de una versión anterior de la app, de
    cuando `pedidos` ya existía pero `TasaCambio` recién se había
    agregado a models.py) y el CREATE TABLE chocó con esa tabla —
    Postgres revierte toda la transacción en ese caso, así que ni
    siquiera las columnas de `pedidos` llegaban a agregarse. Por eso
    cada paso se fija primero, con el inspector, si ya está hecho.
    """
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if not inspector.has_table("tasas_cambio"):
        logger.info("Creando tabla tasas_cambio...")
        op.create_table(
            'tasas_cambio',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('moneda', sa.String(length=8), nullable=False),
            sa.Column('tasa_bolivares', sa.Numeric(precision=18, scale=8), nullable=False),
            sa.Column('fuente', sa.String(length=20), nullable=False),
            sa.Column('fecha_vigencia', sa.Date(), nullable=False),
            sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
            sa.Column('actualizada_automaticamente', sa.Boolean(), nullable=False),
            sa.Column('mensaje_error', sa.Text(), nullable=True),
            sa.Column('activa', sa.Boolean(), nullable=False),
            sa.CheckConstraint('tasa_bolivares > 0', name='ck_tasa_cambio_positiva'),
            sa.PrimaryKeyConstraint('id'),
        )
    else:
        logger.info("La tabla tasas_cambio ya existe — se omite create_table.")

    # Se vuelve a inspeccionar después del create_table (si corrió):
    # el índice se revisa aparte porque la tabla puede existir sin él
    # (por ejemplo, si un intento previo creó la tabla pero se
    # interrumpió antes del create_index).
    indices_existentes = {ix["name"] for ix in sa.inspect(bind).get_indexes("tasas_cambio")}
    if "ix_tasas_cambio_moneda_activa" not in indices_existentes:
        op.create_index('ix_tasas_cambio_moneda_activa', 'tasas_cambio', ['moneda', 'activa'], unique=False)
    else:
        logger.info("El índice ix_tasas_cambio_moneda_activa ya existe — se omite.")

    columnas_pedidos = {c["name"] for c in sa.inspect(bind).get_columns("pedidos")}

    if "tasa_bcv_aplicada" not in columnas_pedidos:
        logger.info("Agregando columna tasa_bcv_aplicada...")
        op.add_column('pedidos', sa.Column('tasa_bcv_aplicada', sa.Numeric(precision=18, scale=8), nullable=True))
    else:
        logger.info("La columna tasa_bcv_aplicada ya existe — se omite.")

    if "total_bolivares" not in columnas_pedidos:
        logger.info("Agregando columna total_bolivares...")
        op.add_column('pedidos', sa.Column('total_bolivares', sa.Numeric(precision=18, scale=2), nullable=True))
    else:
        logger.info("La columna total_bolivares ya existe — se omite.")

    logger.info("Migración completada.")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'total_bolivares')
    op.drop_column('pedidos', 'tasa_bcv_aplicada')
    op.drop_index('ix_tasas_cambio_moneda_activa', table_name='tasas_cambio')
    op.drop_table('tasas_cambio')
    # ### end Alembic commands ###
