"""esquema inicial

Revision ID: 8c1c0d28abfb
Revises: 
Create Date: 2026-07-18 13:04:14.116227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c1c0d28abfb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=120), nullable=False),
    sa.Column('apellidos', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('creada_en', sa.DateTime(), nullable=False),
    sa.Column('actualizada_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clientas_apellidos', 'clientas', ['apellidos'], unique=False)
    op.create_index('ix_clientas_nombres', 'clientas', ['nombres'], unique=False)
    op.create_index('ix_clientas_telefono', 'clientas', ['telefono'], unique=False)
    op.create_table('colores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('codigo_hex', sa.String(length=7), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('configuracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_negocio', sa.String(length=120), nullable=False),
    sa.Column('nombre_administrador', sa.String(length=120), nullable=False),
    sa.Column('dias_credito', sa.Integer(), nullable=False),
    sa.Column('limite_poco_stock', sa.Integer(), nullable=False),
    sa.Column('moneda', sa.String(length=8), nullable=False),
    sa.Column('version_app', sa.String(length=20), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contador_pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siguiente_valor', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('imagen', sa.String(length=255), nullable=True),
    sa.Column('costo_produccion', sa.Integer(), nullable=False),
    sa.Column('precio_publico', sa.Integer(), nullable=False),
    sa.Column('stock_actual', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.CheckConstraint('costo_produccion >= 0', name='ck_producto_costo_no_negativo'),
    sa.CheckConstraint('precio_publico >= 0', name='ck_producto_precio_no_negativo'),
    sa.CheckConstraint('stock_actual >= 0', name='ck_producto_stock_no_negativo'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=60), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('password_salt', sa.String(length=64), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('ultimo_acceso_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_nombre_usuario'), 'usuarios', ['nombre_usuario'], unique=True)
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_pedido', sa.String(length=20), nullable=False),
    sa.Column('clienta_id', sa.Integer(), nullable=False),
    sa.Column('estado_entrega', sa.Enum('PENDIENTE', 'EN_PREPARACION', 'LISTO_PARA_ENTREGAR', 'ENTREGADO', 'CANCELADO', name='estadoentrega', native_enum=False, length=30), nullable=False),
    sa.Column('estado_pago', sa.Enum('PENDIENTE', 'PAGADO', 'CANCELADO', name='estadopago', native_enum=False, length=20), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=False),
    sa.Column('fecha_estimada_entrega', sa.Date(), nullable=True),
    sa.Column('fecha_entrega', sa.Date(), nullable=True),
    sa.Column('fecha_vencimiento_pago', sa.Date(), nullable=True),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('costo_total', sa.Integer(), nullable=False),
    sa.Column('ganancia_total', sa.Integer(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('cancelado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clienta_id'], ['clientas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_pedido')
    )
    op.create_index('ix_pedidos_clienta_id', 'pedidos', ['clienta_id'], unique=False)
    op.create_index('ix_pedidos_estado_entrega', 'pedidos', ['estado_entrega'], unique=False)
    op.create_index('ix_pedidos_estado_pago', 'pedidos', ['estado_pago'], unique=False)
    op.create_index('ix_pedidos_fecha_creacion', 'pedidos', ['fecha_creacion'], unique=False)
    op.create_table('producto_colores',
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colores.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('producto_id', 'color_id')
    )
    op.create_table('movimientos_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('tipo_movimiento', sa.Enum('STOCK_INICIAL', 'ENTRADA', 'SALIDA_PEDIDO', 'DEVOLUCION_CANCELACION', 'AJUSTE_POSITIVO', 'AJUSTE_NEGATIVO', 'CORRECCION', name='tipomovimientoinventario', native_enum=False, length=30), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('stock_anterior', sa.Integer(), nullable=False),
    sa.Column('stock_nuevo', sa.Integer(), nullable=False),
    sa.Column('costo_unitario', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_movimientos_producto_id', 'movimientos_inventario', ['producto_id'], unique=False)
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.Column('metodo_pago', sa.String(length=40), nullable=True),
    sa.Column('referencia', sa.String(length=120), nullable=True),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.CheckConstraint('monto >= 0', name='ck_pago_monto_no_negativo'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pagos_pedido_id', 'pagos', ['pedido_id'], unique=False)
    op.create_table('pedido_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Integer(), nullable=False),
    sa.Column('costo_unitario', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('costo_subtotal', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colores.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedido_items')
    op.drop_index('ix_pagos_pedido_id', table_name='pagos')
    op.drop_table('pagos')
    op.drop_index('ix_movimientos_producto_id', table_name='movimientos_inventario')
    op.drop_table('movimientos_inventario')
    op.drop_table('producto_colores')
    op.drop_index('ix_pedidos_fecha_creacion', table_name='pedidos')
    op.drop_index('ix_pedidos_estado_pago', table_name='pedidos')
    op.drop_index('ix_pedidos_estado_entrega', table_name='pedidos')
    op.drop_index('ix_pedidos_clienta_id', table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_index(op.f('ix_usuarios_nombre_usuario'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('productos')
    op.drop_table('contador_pedidos')
    op.drop_table('configuracion')
    op.drop_table('colores')
    op.drop_index('ix_clientas_telefono', table_name='clientas')
    op.drop_index('ix_clientas_nombres', table_name='clientas')
    op.drop_index('ix_clientas_apellidos', table_name='clientas')
    op.drop_table('clientas')
    # ### end Alembic commands ###
